name: Pipeline de Tesets Auomatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Instalando as Dependências para os testes
        run: npm install
        
      - name: Rodando os testes automatizados de API
        run: npx cypress run
